'use client';

import Link from 'next/link';
import Image from 'next/image';
import { ArrowLeft } from 'lucide-react';

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b border-slate-200">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 py-4">
          <div className="flex items-center justify-between">
            <Link href="/" className="font-bold text-xl text-primary flex items-center">
              <Image 
                src="/logo horizontal purple big.png" 
                alt="ScanContract Logo" 
                width={180}
                height={45}
              />
            </Link>
            <Link href="/" className="flex items-center text-sm text-slate-600 hover:text-primary transition-colors">
              <ArrowLeft className="w-4 h-4 mr-1" />
              Back to Home
            </Link>
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 sm:px-6 py-12">
        <div className="prose max-w-none">
          <h1 className="text-3xl font-bold mb-8 text-slate-900">Privacy Policy</h1>
          
          <p className="text-slate-600 mb-6">Last Updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
          
          <div className="space-y-8">
            <section>
              <h2 className="text-xl font-semibold text-slate-900">1. Introduction</h2>
              <p className="text-slate-600">At ScanContract ("we," "our," or "us"), we respect your privacy and are committed to protecting your personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our website and services.</p>
              <p className="text-slate-600">Please read this Privacy Policy carefully. By using our services, you consent to the practices described in this policy.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900">2. Information We Collect</h2>
              <p className="text-slate-600">We collect several types of information for various purposes:</p>
              
              <h3 className="text-lg font-medium text-slate-800 mt-4">2.1 Personal Information</h3>
              <p className="text-slate-600">When you create an account or use our services, we may collect:</p>
              <ul className="list-disc pl-6 text-slate-600 space-y-2">
                <li>Contact information (such as name, email address)</li>
                <li>Account credentials (password)</li>
                <li>Billing information (payment details)</li>
                <li>User profile data</li>
              </ul>
              
              <h3 className="text-lg font-medium text-slate-800 mt-4">2.2 Contract Data</h3>
              <p className="text-slate-600">When you upload contracts for analysis, we collect:</p>
              <ul className="list-disc pl-6 text-slate-600 space-y-2">
                <li>The content of the contracts</li>
                <li>Metadata related to the contracts</li>
                <li>Analysis results generated by our AI</li>
              </ul>
              
              <h3 className="text-lg font-medium text-slate-800 mt-4">2.3 Usage Information</h3>
              <p className="text-slate-600">We automatically collect information about your interactions with our services:</p>
              <ul className="list-disc pl-6 text-slate-600 space-y-2">
                <li>Log data (IP address, browser type, pages visited, time spent)</li>
                <li>Device information (hardware model, operating system)</li>
                <li>Performance and error data</li>
                <li>Feature usage patterns</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900">3. How We Use Your Information</h2>
              <p className="text-slate-600">We use the information we collect for various purposes, including:</p>
              <ul className="list-disc pl-6 text-slate-600 space-y-2">
                <li>Providing and maintaining our services</li>
                <li>Processing and analyzing contracts</li>
                <li>Improving and personalizing user experience</li>
                <li>Managing user accounts and subscriptions</li>
                <li>Communicating with you about our services</li>
                <li>Detecting and preventing fraud and security issues</li>
                <li>Complying with legal obligations</li>
              </ul>
              
              <h3 className="text-lg font-medium text-slate-800 mt-4">3.1 AI Training and Improvement</h3>
              <p className="text-slate-600">To continuously improve our AI-powered contract analysis:</p>
              <ul className="list-disc pl-6 text-slate-600 space-y-2">
                <li>We may use anonymized and aggregated data derived from contracts to train and improve our AI models.</li>
                <li>All contract data used for AI training is stripped of personally identifiable information and confidential details.</li>
                <li>You can opt out of having your data used for AI training by contacting our support team.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900">4. How We Protect Your Information</h2>
              <p className="text-slate-600">We implement a variety of security measures to maintain the safety of your information:</p>
              <ul className="list-disc pl-6 text-slate-600 space-y-2">
                <li>All data is encrypted in transit and at rest using industry-standard encryption protocols.</li>
                <li>We maintain secure servers with restricted access.</li>
                <li>Regular security assessments and penetration testing.</li>
                <li>Employee access controls and training on data handling practices.</li>
                <li>Contracts are automatically deleted from our active systems 30 days after analysis unless you choose to store them longer.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900">5. Information Sharing and Disclosure</h2>
              <p className="text-slate-600">We do not sell or rent your personal information to third parties. We may share your information in the following circumstances:</p>
              
              <h3 className="text-lg font-medium text-slate-800 mt-4">5.1 Service Providers</h3>
              <p className="text-slate-600">We may share information with trusted third-party service providers who assist us in operating our website, conducting business, or servicing you, so long as those parties agree to keep this information confidential.</p>
              
              <h3 className="text-lg font-medium text-slate-800 mt-4">5.2 Business Transfers</h3>
              <p className="text-slate-600">If we are involved in a merger, acquisition, or sale of all or a portion of our assets, your information may be transferred as part of that transaction.</p>
              
              <h3 className="text-lg font-medium text-slate-800 mt-4">5.3 Legal Requirements</h3>
              <p className="text-slate-600">We may disclose your information if required to do so by law or in response to valid requests by public authorities (e.g., a court or a government agency).</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900">6. Your Data Rights and Choices</h2>
              <p className="text-slate-600">Depending on your location, you may have certain rights regarding your personal information:</p>
              <ul className="list-disc pl-6 text-slate-600 space-y-2">
                <li>Access and review your personal information</li>
                <li>Update or correct inaccurate data</li>
                <li>Delete your personal information</li>
                <li>Export your data in a portable format</li>
                <li>Restrict or object to certain processing activities</li>
                <li>Withdraw consent where applicable</li>
              </ul>
              <p className="text-slate-600 mt-3">To exercise these rights, please contact us using the information provided at the end of this policy.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900">7. Cookies and Tracking Technologies</h2>
              <p className="text-slate-600">We use cookies and similar tracking technologies to collect information about your browsing activities and to remember your preferences. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900">8. Children's Privacy</h2>
              <p className="text-slate-600">Our services are not intended for children under the age of 18. We do not knowingly collect personal information from children under 18. If you are a parent or guardian and believe we may have collected information about a child, please contact us.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900">9. International Data Transfers</h2>
              <p className="text-slate-600">Your information may be transferred to — and maintained on — computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ. If you are located outside the United States and choose to provide information to us, please note that we transfer the information to the United States and process it there.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900">10. Changes to This Privacy Policy</h2>
              <p className="text-slate-600">We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last Updated" date. You are advised to review this Privacy Policy periodically for any changes.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900">11. Contact Us</h2>
              <p className="text-slate-600">If you have any questions about this Privacy Policy, please contact us at:</p>
              <p className="text-slate-600">privacy@scancontract.com</p>
            </section>
          </div>
        </div>
      </main>

      <footer className="bg-slate-50 border-t border-slate-200 py-8">
        <div className="max-w-6xl mx-auto px-4 sm:px-6">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <p className="text-sm text-slate-500">© {new Date().getFullYear()} ScanContract. All rights reserved.</p>
            <div className="flex space-x-6 mt-4 md:mt-0">
              <Link href="/privacy" className="text-sm text-slate-500 hover:text-primary">Privacy Policy</Link>
              <Link href="/terms" className="text-sm text-slate-500 hover:text-primary">Terms of Service</Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
} 